# 🎬 Movie Revenue Analysis

## Objective
Analyze how **budget, genre, and release year** impact movie revenue.

## Dataset
Kaggle Movies Dataset

## Key Questions
- Do higher budgets lead to higher revenue?
- Which genres perform best?

In [1]:
import pandas as pd

In [2]:
import ast

In [3]:
df = pd.read_csv("movies_metadata.csv", low_memory=False)

In [ ]:
#Creating a dataframe with the following collumns

In [4]:
df = df[["title", "budget", "revenue", "release_date", "genres"]]

In [5]:
df.head()

,title,budget,revenue,release_date,genres
0,Toy Story,30000000,373554033.0,1995-10-30,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '..."
1,Jumanji,65000000,262797249.0,1995-12-15,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
2,Grumpier Old Men,0,0.0,1995-12-22,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ..."
3,Waiting to Exhale,16000000,81452156.0,1995-12-22,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
4,Father of the Bride Part II,0,76578911.0,1995-02-10,"[{'id': 35, 'name': 'Comedy'}]"

In [ ]:
# Converting revenue and budget type to number if something cannot be converted it turns it to  NaN(missing value)

In [6]:
df["budget"] = pd.to_numeric(df["budget"], errors="coerce")
df["revenue"] = pd.to_numeric(df["revenue"], errors="coerce")

In [7]:
df.head()

,title,budget,revenue,release_date,genres
0,Toy Story,30000000.0,373554033.0,1995-10-30,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '..."
1,Jumanji,65000000.0,262797249.0,1995-12-15,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
2,Grumpier Old Men,0.0,0.0,1995-12-22,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ..."
3,Waiting to Exhale,16000000.0,81452156.0,1995-12-22,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
4,Father of the Bride Part II,0.0,76578911.0,1995-02-10,"[{'id': 35, 'name': 'Comedy'}]"

In [ ]:
# keeping only rows where both budget and revenue is greater than 0

In [9]:
df = df[(df["budget"]>0) & (df["revenue"]>0)]

In [10]:
df.head()

,title,budget,revenue,release_date,genres
0,Toy Story,30000000.0,373554033.0,1995-10-30,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '..."
1,Jumanji,65000000.0,262797249.0,1995-12-15,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
3,Waiting to Exhale,16000000.0,81452156.0,1995-12-22,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
5,Heat,60000000.0,187436818.0,1995-12-15,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam..."
8,Sudden Death,35000000.0,64350171.0,1995-12-22,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."

In [ ]:
#takes the date and converts it to proper date and extracts only the year if value invalid becomes NaT(missing value)

In [15]:
df["release_year"] = pd.to_datetime(df["release_date"], errors = "coerce").dt.year

In [ ]:
#converts text inot a real python object an extracts the first genre from the list of genres in the data and creates a separate column wiht it.

In [18]:
def get_genre(x):
    try:
        genres = ast.literal_eval(x)
        return genres[0]["name"] if genres else None
    except:
        return None

df["genre"] = df["genres"].apply(get_genre)

In [19]:
df.head()

,title,budget,revenue,release_date,genres,release_year,genre
0,Toy Story,30000000.0,373554033.0,1995-10-30,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",1995,Animation
1,Jumanji,65000000.0,262797249.0,1995-12-15,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",1995,Adventure
3,Waiting to Exhale,16000000.0,81452156.0,1995-12-22,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995,Comedy
5,Heat,60000000.0,187436818.0,1995-12-15,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",1995,Action
8,Sudden Death,35000000.0,64350171.0,1995-12-22,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",1995,Action

In [ ]:
#removing rows where the release year or genre is missing
#then saves data into a csv file

In [20]:
df = df.dropna(subset = ["release_year", "genre"])

df.to_csv("clean_movies.csv", index = False)

print("Done! Clean dataset saved as clean_movies.csv")

Done! Clean dataset saved as clean_movies.csv

In [ ]:
# sorts values by release year in ascending order

In [22]:
df_sorted = df.sort_values(by = "release_year", ascending = False)
df_sorted.head()

,title,budget,revenue,release_date,genres,release_year,genre
42168,John Wick: Chapter 2,40000000.0,171539887.0,2017-02-08,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",2017,Thriller
43206,Aftermath,10500000.0,3451.0,2017-04-06,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",2017,Drama
42853,Life,58000000.0,100541806.0,2017-03-22,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",2017,Horror
42901,Power Rangers,100000000.0,142337240.0,2017-03-23,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2017,Action
42902,Alien: Covenant,97000000.0,232380243.0,2017-05-09,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",2017,Horror

In [23]:
df["release_year"].max()

2017